name: build-update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Repository keepalive
        uses: gautamkrishnar/keepalive-workflow@1.0.10
        with:
          committer_email: gkr@vond.net

  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo 'aur.archlinux.org 95.216.144.15' >> /etc/hosts
      - run: docker build --pull --no-cache aurutils -t aurutils
      - run: |
          docker run --rm \
          -e SSH_CONFIG_BASE64="${{ secrets.SSH_CONFIG_BASE64 }}" \
          -e SSH_KEY_BASE64="${{ secrets.SSH_KEY_BASE64 }}" \
          -e SSH_PORT="${{ secrets.SSH_PORT }}" \
          -v "${PWD}/updatepkgs.sh:/updatepkgs.sh:ro" \
          -v "${PWD}/zfs-linux-lts:/zfs-linux-lts:ro" \
          aurutils /bin/bash /updatepkgs.sh
